services:
  - type: web
    name: taboo-backend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
